# Generated by Django 6.0 on 2026-01-24 13:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PastQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='e.g., 2023 for 2022/2023 academic year', verbose_name='academic year')),
                ('semester', models.CharField(choices=[('first', 'First Semester'), ('second', 'Second Semester'), ('summer', 'Summer Semester'), ('unknown', 'Unknown')], default='first', max_length=20, verbose_name='semester')),
                ('exam_type', models.CharField(choices=[('midterm', 'Midterm Exam'), ('final', 'Final Exam'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('test', 'Test'), ('other', 'Other')], default='final', max_length=20, verbose_name='exam type')),
                ('title', models.CharField(blank=True, help_text='Optional descriptive title', max_length=200, verbose_name='title')),
                ('file', models.FileField(help_text='PDF or Image files only (max 10MB)', upload_to='past_questions/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='file')),
                ('file_size', models.IntegerField(default=0, help_text='Size in bytes', verbose_name='file size')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='original filename')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable', verbose_name='rejection reason')),
                ('download_count', models.IntegerField(default=0, verbose_name='download count')),
                ('view_count', models.IntegerField(default=0, verbose_name='view count')),
                ('lecturer', models.CharField(blank=True, help_text='Name of lecturer/professor', max_length=100, verbose_name='lecturer')),
                ('has_solutions', models.BooleanField(default=False, help_text='Does this include solutions/answers?', verbose_name='has solutions')),
                ('is_scanned', models.BooleanField(default=False, help_text='Is this a scanned document?', verbose_name='is scanned')),
                ('quality_rating', models.FloatField(default=0.0, help_text='Average user rating (0-5)', verbose_name='quality rating')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_questions', to='courses.course', verbose_name='course')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_past_questions', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_past_questions', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'past question',
                'verbose_name_plural': 'past questions',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to=settings.AUTH_USER_MODEL)),
                ('past_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_history', to='past_questions.pastquestion')),
            ],
            options={
                'verbose_name_plural': 'Download Histories',
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pastquestion',
            index=models.Index(fields=['status', 'uploaded_at'], name='past_questi_status_759353_idx'),
        ),
        migrations.AddIndex(
            model_name='pastquestion',
            index=models.Index(fields=['course', 'year', 'semester'], name='past_questi_course__80c204_idx'),
        ),
        migrations.AddIndex(
            model_name='pastquestion',
            index=models.Index(fields=['uploaded_by'], name='past_questi_uploade_d49ce3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pastquestion',
            unique_together={('course', 'year', 'semester', 'exam_type', 'file_name')},
        ),
    ]
