# Generated by Django 6.0 on 2026-01-24 00:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('index_number', models.CharField(error_messages={'unique': 'A user with that index number already exists.'}, help_text='Required. Your university index number.', max_length=20, unique=True, verbose_name='index number')),
                ('faculty', models.CharField(blank=True, max_length=100, verbose_name='faculty')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='department')),
                ('level', models.CharField(blank=True, max_length=10, verbose_name='level')),
                ('is_admin', models.BooleanField(default=False, verbose_name='admin status')),
                ('is_moderator', models.BooleanField(default=False, verbose_name='moderator status')),
                ('reputation_score', models.IntegerField(default=0, verbose_name='reputation score')),
                ('upload_count', models.IntegerField(default=0, verbose_name='upload count')),
                ('successful_uploads', models.IntegerField(default=0, verbose_name='successful uploads')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='profile picture')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='phone number')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='email notifications')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['index_number'],
            },
        ),
    ]
