# Generated by Django 6.0.1 on 2026-01-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_created_at_user_deleted_at_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='download_count',
            field=models.IntegerField(default=0, verbose_name='download count'),
        ),
    ]
