# Generated by Django 6.0 on 2026-01-24 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., CSC101, MAT101, PHY101', max_length=20, unique=True, verbose_name='course code')),
                ('title', models.CharField(help_text='Full course title', max_length=200, verbose_name='course title')),
                ('faculty', models.CharField(choices=[('science', 'Physical Sciences'), ('engineering', 'Engineering & Technology'), ('medicine', 'Health Sciences'), ('arts', 'Arts & Humanities'), ('business', 'Business & Law'), ('agriculture', 'Agriculture'), ('education', 'Education'), ('social', 'Social Sciences')], max_length=50, verbose_name='faculty')),
                ('department', models.CharField(help_text='Department offering the course', max_length=100, verbose_name='department')),
                ('level', models.CharField(help_text='e.g., 100, 200, 300, 400', max_length=10, verbose_name='level')),
                ('semester', models.CharField(choices=[('first', 'First Semester'), ('second', 'Second Semester'), ('both', 'Both Semesters')], default='first', max_length=20, verbose_name='semester')),
                ('credit_hours', models.PositiveSmallIntegerField(default=3, help_text='Number of credit hours', verbose_name='credit hours')),
                ('description', models.TextField(blank=True, help_text='Course description and objectives', verbose_name='description')),
                ('is_active', models.BooleanField(default=True, help_text='Is this course currently being offered?', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='courses_cou_code_612388_idx'), models.Index(fields=['faculty', 'level'], name='courses_cou_faculty_ed9f32_idx'), models.Index(fields=['department'], name='courses_cou_departm_9688c2_idx')],
            },
        ),
    ]
