# Generated by Django 6.0.1 on 2026-01-31 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_past_questions',
            field=models.IntegerField(default=0, null=True, verbose_name="course's past questions"),
        ),
    ]
